[package]
name = "ddo-fjs-rel"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"]}
ddo = "2.0.0"
num_cpus = "1.16.0"
ordered-float = "5.0.0"
rand = "0.9.1"
thiserror = "2.0.12"
